### ISSUE TITLE
Connect call Failed

### ISSUE THREAD

**Issue by pogrammar** [Pysics/akinator.py#3]
### Summary

When using asynchronous Akinator, it wont connect to en.akinator.com

### Reproduction Steps

I followed the example https://github.com/Infiniticity/akinator.py/blob/main/examples/async_aki.py, 
by adding the lib code into my own files, but async_aki is fetched from this repo itself...

### Minimal Reproducible Code

```python
Cannot connect to host en.akinator.com:443 ssl:default [Connect call failed ('2600:1f11:f39:6f3f:ad82:13e1:7fed:7818', 443, 0, 0)]
```

### Expected Results

It was expected to post an embedded akinator game into discord... 
![image](https://github.com/Infiniticity/akinator.py/assets/97349629/3a1d9f68-e44c-4ead-b5f2-8406d0b1c7f0)

### Actual Results

it just fails..., with the error: 

`Cannot connect to host en.akinator.com:443 ssl:default [Connect call failed ('2600:1f11:f39:6f3f:ad82:13e1:7fed:7818', 443, 0, 0)]`

![image](https://github.com/Infiniticity/akinator.py/assets/97349629/09fed097-368b-4cf9-8a1e-a3e5744f04e6)

### System Information

It runs on a pterodactyl hosting service

### Checklist

- [X] I have searched open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have made sure that this issue is valid.

### Additional Context

For context of this issue, i have been implementing it in a discord bot.

**Comment by Ombucha** [comment]
I am not able to reproduce this error locally. Are you still facing this issue?

**Comment by pogrammar** [comment]
yes i am facing it... The screenshot is from before when it used to work but one day it just broke... do you know how to fix it?

**Comment by pogrammar** [comment]
can you show your code where you tried to reproduce it?

**Comment by Ombucha** [comment]
I am using the [example code](https://github.com/Infiniticity/akinator.py/blob/main/examples/async_aki.py).

**Comment by japandotorg** [comment]
Same has been happening to me `ClientConnectorError: Cannot connect to host en.akinator.com:443 ssl:default 
[Network is unreachable]`, I can ensure that it wasn't an issue a few months ago.

**Comment by japandotorg** [comment]
Here's the minimal code I'm using for reproduction.
![image](https://github.com/Infiniticity/akinator.py/assets/78662983/cbe197eb-73f4-46bb-bf97-0185a59aec35)

**Comment by pogrammar** [comment]
@Infiniticity I am still facing the error...

**Comment by japandotorg** [comment]
it's actually a problem with the akinator api servers, not the library

**Comment by Ombucha** [comment]
Yeah, I don't think this is a fixable issue.

**Comment by pogrammar** [comment]
Then how is @Infiniticity able to do it locally with no errors
